# Generated by Django 2.1.4 on 2019-01-03 11:48

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar_href',
            field=models.ImageField(null=True, upload_to=user.models.user_profile_avatar_path),
        ),
    ]
