# Generated by Django 2.1.4 on 2018-12-20 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('ballot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_at', models.DateTimeField(null=True)),
                ('close_at', models.DateTimeField(null=True)),
                ('count_at', models.DateTimeField(null=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot.Ballot')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org')),
                ('prev_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='poll.Proposal')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Proposal'),
        ),
    ]
