# Generated by Django 2.1.4 on 2018-12-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='org',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='prev_version',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='org',
        ),
        
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
